<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Title</title>
		<link rel="stylesheet" type="text/css" href="/css/styles.css">
		<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap-theme.min.css">
		<script src="/js/jquery.js"></script>
		<script src="/bootstrap/js/bootstrap.min.js"></script>
	</head>
	<body>
		<?php //Подключение header ?>
		<?php $this->partial('partial/header', array());?>

		<div style="width: 960px; margin: 0px auto; height: 200px;">
			<?php //Вывод флеш сообщений ?>
			<?php $this->flashSession->output() ?>
		
			<?php //Вывод контента ?>
			<?php echo $this->getContent() ?>
		</div>
		<?php //Подключение footer ?>
		<?php $this->partial('partial/footer', array());?>
	</body>
</html>