<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Admin panel</title>
</head>
<body>
	
	<div id="panel">
		<div class="container">
			<div class="row">
				<div class="col">
					<h1 v-once>{{title}}</h1>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="inputs">
				<input type="text" placeholder="title" v-model="itemTitle">
				<br>
				<input type="text" placeholder="desc" v-model="itemDesc">
				<br>
				<input type="submit" v-on:click.prevent="addItem">
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="card" v-for="item in items">
					<div class="card_block">
						<h3>{{item.title}}</h3>
						<p>{{item.desc}}</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>
	<script src="/admin/js/main.js"></script>
</body>
</html>